{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $databaseUser := printf ""}}
{{- $databasePassword := printf ""}}
{{- $urlEncodedDatabasePassword := printf ""}}
{{- $host := printf ""}}
{{- $databaseName := printf ""}}
{{- $hostWithoutPort := printf ""}}
{{- $pgbouncerUrl := printf ""}}
{{- $secretName := printf "%s-pguser-%s" .Values.global.databaseAlias .Values.global.config.databaseUser }}
{{- $databaseUser = .Values.global.config.databaseUser}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if not $secretObj }}
  {{- fail (printf "Secret %s not found in namespace %s" $secretName .Release.Namespace) }}
{{- end }}
{{- $secretData := (get $secretObj "data") }}
{{- if not $secretData }}
  {{- fail (printf "Secret %s data not found in namespace %s" $secretName .Release.Namespace) }}
{{- end }}
{{- $databasePassword = b64dec (get $secretData "password") }}
{{- $urlEncodedDatabasePassword = $databasePassword | urlquery }}
{{- $databaseName = b64dec (get $secretData "dbname") }}
{{- $pgbouncerUrl = b64dec (get $secretData "pgbouncer-uri") }}
{{- $host = printf "%s:%s" (b64dec (get $secretData "host")) (b64dec (get $secretData "port")) }}
{{- $hostWithoutPort = printf "%s" (b64dec (get $secretData "host"))  }}
{{- $databaseJDBCURL := printf "jdbc:postgresql://%s:%s@%s/%s" $databaseUser $databasePassword $host $databaseName }}
{{- $databaseJDBCURLNoCreds := printf "jdbc:postgresql://%s/%s" $host $databaseName }}

{{- $databasePrismaURL := printf "%s?schema=%s" $pgbouncerUrl $databaseName }}
{{- $databasePrismaDirectURL := printf "postgres://%s:%s@%s/%s?schema=%s" $databaseUser $urlEncodedDatabasePassword $host $databaseName $databaseName }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  POSTGRES_PASSWORD: {{ $databasePassword | b64enc | quote }}
  POSTGRES_USER: {{ $databaseUser | b64enc | quote }}
  POSTGRES_DATABASE: {{ $databaseName | b64enc | quote }}
  POSTGRES_HOST: {{ $hostWithoutPort | b64enc | quote }}
  PGBOUNCER_URL: {{ $pgbouncerUrl | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-prisma-migrate
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  DATABASE_URL: {{ $databasePrismaURL | b64enc | quote }}
  DATABASE_DIRECT_URL: {{ $databasePrismaDirectURL | b64enc | quote }}
{{- end }}
